---
title: "Laboratorio 1- Econometria en R"
output: html_notebook
---

## Problema 1

```{r}
install.packages("modeest")
```

```{r}
library(stringr)
library(modeest)
```

```{r}
# 1. ¿Cómo generaría un arreglo aleatorio de 250 elementos con los colores primarios?

colores_primarios <- c("rojo","amarillo","azul")
colores_aleatorios <- sample(colores_primarios, 250, replace = TRUE)
colores_aleatorios
```

```{r}
# 2. Dado un arreglo de 120000 elementos de números enteros entre 40 y 70, ¿Cómo haría para obtener la desviación estándar de aquellos números que son mayores a 55 y menores a 64?

a <- sample(40:70, 120000, replace = TRUE)
a_prima <-  a[a > 55 & a < 64]
sd(a_prima)
```

```{r}
# 3. Suponga que se almacena en una variable un arreglo con todos los números de carnet de los estudiantes del Instituto de Investigación de Operaciones de la universidad en forma de string, los carnets tiene al inicio dos caracteres que identifican el año en el que la persona entró a la universidad por ejemplo: 19004528 hacer referencia a una persona que ingreso en el año 2019, 06009878 hace referencia a una persona que ingreso que el año 2006, ¿Cómo haría para contar la cantidad de alumnos por año?

year <- sample(01:23, 100, replace =TRUE)
year <- sprintf("%02d", year)
correlativo <- sample(0:999999, 100, replace=TRUE)
correlativo <- sprintf("%06d", correlativo)
carnets <- paste(year, correlativo, sep = "")
conteo <- table(substr(carnets, 1, 2))
conteo
```

```{r}
# 4. Define el vector y = (1, 3, 5, 7) utilizando la función c(). ¿Cómo lo harías con la función seq()?

y <- c(1, 3, 5, 7)
yp <- seq(from = 1, to = 7, by =2)
yp
```

```{r}
# 5. Si b <- list(a=1:10, c="Hola", d="XX"), escriba una expresión en R que devuelva todos los elementos de la lista excepto los elementos 4,6,7,8 del vector a.
b <- list(a=1:10, c="Hola", d="XX")
b$a[c(-4,-6,-7,-8)]
```

```{r}
# 6. Dado los siguientes vectores, muestre el código en R necesario para declarar y calcular el promedio, deviación estándar, mediana, moda y sumatoria total para los siguientes vectores: a.x=(8,7,6,5) b. y = (3,3, 3, 3, 3, 3, 3, 3, 2, 2) c. z = (1, 1.75, 2.5, 3.25, 4)

x <- c(8, 7, 6, 5)
y <- c(3, 3, 3, 3, 3, 3, 3, 3, 2, 2)
z <- c(1, 1.75, 2.5, 3.25, 4)

#Medias
mean(x)  
mean(y)  
mean(z)  

#Desviación estándar
sd(x)  
sd(y)  
sd(z)

#Mediana
median(x)  
median(y)  
median(z)

#Moda
mfv(x)  
mfv(y)  
mfv(z)  

#Sumatoria
sum(x)
sum(y)  
sum(z) 

```

```{r}
# 7. Sabemos que para sumar vectores estos deben tener la misma longitud. Sin embargo R trabaja de manera distinta. Defina los vectores x = (1, 2, 3, 4, 5, 6), y = (7, 8), z = (9, 10, 11, 12). Calcula: a. x + x b. x + y c. Responda ¿Qué ha hecho R?

x <- c(1, 2, 3, 4, 5, 6)
y <- c(7,8)
z <- c(9, 10, 11, 12)

print(x+x)
print(x+y)
print("Cuando R realiza operaciones aritméticas entre vectores con diferente longitud, recicla los elementos del vector de menor longitud hasta coincidir con la longitud del mayor")

```

```{r}
# 8. Dada la variable string <- "Hola Mundo", escriba una instrucción en R que devuelva la siguiente salida: [[1]] [1] "Hola" [[2]] [1] "Mundo"

mensaje <- "Hola Mundo"
palabras <- strsplit(mensaje, " ")
print(palabras[[1]][[1]])
print(palabras[[1]][[2]])

```

## Problema 2

```{r}
load('data.Rdata')
```

```{r}
# 1. ¿Qué tipo de dato es info_estudiantes?
class(info_estudiantes)
```

```{r}
# 2. ¿Cuantos elementos tiene info_estudiantes?
length(info_estudiantes)
# el valor que la funcion retorna es 3, revisando los contenidos de la estructura de datos, destaca que cada uno de estos tres elementos corresponde a una columna de la estructura, por lo que para tener una mejor nocion de la cantidad de datos contenidos, ejecuto length sobre uno de sus elementos
length(info_estudiantes[[1]])
```

```{r}
# 3. ¿Qué representa cada uno de los elementos de info_estudiantes?
# Los elementos o vectores contenidos dentro de info_estudiantes representan el carnet, promedio y categoria o tipo de estudiante de un total de 8000 estudiantes
```

```{r}
# 4. ¿Cuál es la media de los estudiantes ingresados en el año 2019? 
mean(info_estudiantes$promedio[substr(info_estudiantes$carnet,1,2) =="19"])

```

```{r}
# 5. ¿Cuál es la suma de desviación estándar de los estudiantes que ingresaron en el año 2016 y 2018?
sum(sd(info_estudiantes$promedio[(substr(info_estudiantes$carnet,1,2) == "18")]), sd(info_estudiantes$promedio[(substr(info_estudiantes$carnet,1,2) == "16")]))

```

```{r}
# 6. ¿Cuál es el mínimo de notas de aquellos estudiantes donde su carnet termina con los números 45 a 48?
v1 <- info_estudiantes$promedio[(substr(info_estudiantes$carnet,7,8)) == "45"]
v2 <- info_estudiantes$promedio[(substr(info_estudiantes$carnet,7,8)) == "48"]
v3 <- c(v1, v2)
min(v3)

```

```{r}
# 7. ¿Cuál es la probabilidad de que un estudiante tipo A tenga una nota mayor a 85?
prob <- sum(info_estudiantes$promedio[info_estudiantes$tipo == 'A'] > 85)/sum(info_estudiantes$tipo == 'A')
print(paste("La probabilidad es del", prob*100, "%"))

```

```{r}
# 8. ¿Cuál es la probabilidad de que un estudiante tipo C haya ingresado en el año 2017 o 2019?
prob2 <- sum(info_estudiantes$tipo[(substr(info_estudiantes$carnet,1,2) == '19') | (substr(info_estudiantes$carnet,1,2) == '17')] == 'C')/sum(info_estudiantes$tipo == 'C')
print(paste("La probabilidad es del", prob2*100, "%"))



```
